### ISSUE TITLE
Error in /yii3.demo/public/ We were unable to find the page /yii3.demo/public/

### ISSUE THREAD

**Issue by bilginnet** [yiisoft/yii-demo#35] opened 2019-12-13 09:09 UTC
### What steps will reproduce the problem?
Error in /yii3.demo/public/ 

We were unable to find the page /yii3.demo/public/

how can i view that views folder  ?

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0.?
| PHP version      | 7,4,0
| Operating system | win10 - xampp

**Comment by roxblnfk** [comment] 2019-12-13 16:04
duplicate of #11

**Closed** 2019-12-13 19:53 UTC

**Comment by sup-ham** [comment] 2020-01-25 20:17
This caused by the dots character. I faced this before.
see https://gist.github.com/sup-ham/5b132ce4547b43aa8b2d#file-router-php-L20-L25
